### ISSUE TITLE
unknown class hash error

### ISSUE THREAD

**Issue by iraklio** [xJonathanLEI/starkli#93]
running a command:

starkli account fetch 0x06d29c77f821a7fcfd10f63cae5d4e6813667b3988593f409fe049930966fd11 --output ~/.starkli-wallets/deployer/account.json

getting an error:

0x036078334509b514626504edc9fb252328d1a240e4e948bef8d0c08dff45927f is not a known account class hash.
Error: unknown class hash: 0x036078334509b514626504edc9fb252328d1a240e4e948bef8d0c08dff45927f

contract is deployed:
https://sepolia.starkscan.co/contract/0x06d29c77f821a7fcfd10f63cae5d4e6813667b3988593f409fe049930966fd11

**Comment by huynhducduy** [comment]
For safety reasons, Starkli only supports well-known account contracts. You can find the list of supported contracts here: https://github.com/xJonathanLEI/starkli/blob/master/src/account.rs#L23-L109

**Comment by iraklio** [comment]
Thanks for getting back. I am using Argent X version 5.17.3 to deploy the account. Do I need downgrade it to version 5.13.1?  


These are the ArgentX versions listed in account.rs file:

    KnownAccountClass {
        class_hash: felt!("0x01a736d6ed154502257f02b1ccdf4d9d1089f80811cd6acad48e6b6a9d1f2003"),
        variant: AccountVariantType::Argent,
        description: "Argent X official account (as of 5.7.0)",
    },
    KnownAccountClass {
        class_hash: felt!("0x029927c8af6bccf3f6fda035981e765a7bdbf18a2dc0d630494f8758aa908e2b"),
        variant: AccountVariantType::Argent,
        description: "Argent X official account (as of 5.13.1)",
    },

**Comment by huynhducduy** [comment]
@iraklio I actually opened a PR to add it to the known classes, and I am waiting for the maintainer to merge https://github.com/xJonathanLEI/starkli/pull/92

**Comment by iraklio** [comment]
Thanks, ETA on when this is expected?

**Comment by xJonathanLEI** [comment]
Fixed by #92.

**Comment by agserran** [comment]
I still have this problem

**Comment by jorgezerpa** [comment]
hi @xJonathanLEI I still have the same error

Command executed:
starkli account fetch 0x0416575467BBE3E3D1ABC92d175c71e06C7EA1FaB37120983A08b6a2B2D12794 --output ~/.starkli-wallets/deployer/account.json --rpc https://starknet-sepolia.infura.io/v3/b26a78bcb38b4957a68b3cdc645c2547

the error:
0x036078334509b514626504edc9fb252328d1a240e4e948bef8d0c08dff45927f is not a known account class hash. If you believe this is a bug, submit a PR to:
    https://github.com/xJonathanLEI/starkli

My starkly version 0.3.3 (1a028fb)

**Comment by oscarwroche** [comment]
I have the same bug:

```
➜  ~ starkli account fetch 0x06335eB5f742e9761ab67C6573B66b68b4c12EaBd86a74E0C1E2c11e3b1A1648 --output ~/.starkli-wallets/deployer/account.json --rpc https://starknet-sepolia.infura.io/v3/1zrSuCVamLIX9QuyygM2MgS1uo7
0x036078334509b514626504edc9fb252328d1a240e4e948bef8d0c08dff45927f is not a known account class hash. If you believe this is a bug, submit a PR to:
    https://github.com/xJonathanLEI/starkli
Error: unknown class hash: 0x036078334509b514626504edc9fb252328d1a240e4e948bef8d0c08dff45927f
➜  ~ starkli --version
0.3.3 (1a028fb)
```

**Comment by oscarwroche** [comment]
@agserran @jorgezerpa this happens because the fix above hasn't been released yet.
Install `starkli` from source: https://book.starkli.rs/installation#install-from-source and try again :)

**Comment by jorgezerpa** [comment]
Hey @oscarwroche it Works perfectly!! thanks a lot :) 

@agserran simply run:
'cargo install --locked --git https://github.com/xJonathanLEI/starkli'

then restart the terminal and try again
